### ISSUE TITLE
Leaves orphaned windows open after using picker

### ISSUE THREAD

**Issue by yetanotherrandomusername** [leehooi/vs-color-picker#1]
This is the first time I've left an issue on GitHub so apologies if I've missed any conventions.

The extension is great but a minor niggle is that it leaves a window open whenever I use it. It is no problem cycling through with Alt-Tab and closing these but it would be better if they didn't get left open.

**Comment by DSCJeremy** [comment]
+1

**Comment by leehooi** [comment]
This is the first issue I got on GitHub too :laughing: . 
Thanks for your comments, I just committed the code to fix this issue. Hope it works.
