### ISSUE TITLE
leaves behind "zombie" processes, i guess.

### ISSUE THREAD

**Issue by bobmagicii** [leehooi/vs-color-picker#4]
code isn't even running anymore. 

![image](https://cloud.githubusercontent.com/assets/881944/22864505/598ad766-f118-11e6-8594-4b174b8cd5f1.png)

for the most part i almost never noticed the picker showing up, turns out it was popping up behind code.

![image](https://cloud.githubusercontent.com/assets/881944/22864519/88266108-f118-11e6-9e36-ae1912742a11.png)

**Comment by leehooi** [comment]
@bobmagicii  Could you leave more information that how this reproduced?

**Comment by bobmagicii** [comment]
open a css file.
type background-color: #
wait for the popup, click the colour chooser button
repeat many times while working in file
close vscode
zombies.

**Comment by leehooi** [comment]
I think this issue has been fixed since last commit. Have a try with latest version.

**Comment by raymyid** [comment]
解决了吗？貌似还是这样啊。关掉 vscode 进程还在的！

![](https://cloud.githubusercontent.com/assets/15687792/23438086/69a20ed6-fe4b-11e6-9ab1-44d68c0810c7.png)

**Comment by leehooi** [comment]
@xiaoruicode 怎么重现的？ColorPicker的窗口一旦失去焦点就会退出进程的。

**Comment by xiaoruicode** [comment]
我是在复制粘贴颜色值的时候出现的，如下图：

![](https://cloud.githubusercontent.com/assets/15687792/23453738/71d99caa-fea4-11e6-9db4-f3bd4fb3ebcc.gif)

**Comment by leehooi** [comment]
@xiaoruicode 我提交了新的版本修复这个问题，你试试。
